name: Test Workflow

on:
  push:
    branches:
    - dev
    - dev-cicd
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4.2.1

    - name: Added the .env file
      uses: ./.github/actions/Env
      with:
        REACT_APP_FRONTEND: ${{ secrets.REACT_APP_FRONTEND }}
        REACT_APP_LOCALBACKEND: ${{ secrets.REACT_APP_LOCALBACKEND }}
        REACT_APP_LOCALDASHBOARD: ${{ secrets.REACT_APP_LOCALDASHBOARD }}
        REACT_APP_IMAGE_URL: ${{ secrets.REACT_APP_IMAGE_URL }}

    - name: Install Dependencies
      uses: ./.github/actions/Build

  Push:
    runs-on: Linux
    timeout-minutes: 2
    needs: build
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 1

    - name: Push Build file to nginx server
      uses: ./.github/actions/Push

  Slack-notification:
    runs-on: ubuntu-latest
    needs: [ build, Push ]
    if: failure()
    steps:
    - name: Slack Notification
      run: |
        echo "Sending Slack notification for failed build..."
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Build Failed Notification",
          "attachments": [
            {
              "fields": [
                {
                  "title": "Commit ID",
                  "value": "${{ github.sha }}",
                  "short": true
                },
                {
                  "title": "Branch Name",
                  "value": "${{ github.ref }}",
                  "short": true
                },
                {
                  "title": "Pushed By",
                  "value": "${{ github.actor }}",
                  "short": true
                },
                {
                  "title": "GitHub URL",
                  "value": "${{ github.server_url }}/${{ github.repository }}",
                  "short": false
                },
                {
                  "title": "Build ID",
                  "value": "${{ github.run_id }}",
                  "short": true
                },
                {
                  "title": "Job URL",
                  "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "short": false
                }
              ]
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}

